package recipes

var backendRegistry = map[string]bool{
	"claude": true,
	"codex":  true,
	"gemini": true,
	"relay":  true,
}

var defaultBackendProfiles = map[string]map[string]any{
	"codex-deep": {
		"id":           "codex-deep",
		"backend":      "codex",
		"model":        "gpt-5.5",
		"effort":       "xhigh",
		"description":  "Deep code reasoning and high-stakes implementation review.",
		"capabilities": []any{"code", "reasoning", "long-form-review"},
	},
	"codex-fast": {
		"id":           "codex-fast",
		"backend":      "codex",
		"model":        "gpt-5.5",
		"effort":       "medium",
		"description":  "Fast code reasoning, facilitation, and reducer work.",
		"capabilities": []any{"code", "reasoning", "facilitation"},
	},
	"claude-code": {
		"id":           "claude-code",
		"backend":      "claude",
		"model":        nil,
		"effort":       nil,
		"description":  "Claude Code session with strong editing and synthesis behavior.",
		"capabilities": []any{"code", "synthesis"},
	},
	"gemini-vision": {
		"id":           "gemini-vision",
		"backend":      "gemini",
		"model":        nil,
		"effort":       nil,
		"description":  "Gemini profile for visual, screenshot, and image-heavy questions.",
		"capabilities": []any{"vision", "large-context"},
	},
	"relay-review": {
		"id":           "relay-review",
		"backend":      "relay",
		"model":        "review-panel",
		"effort":       "2",
		"description":  "Composite relay backend using the review-panel recipe.",
		"capabilities": []any{"composite", "debate"},
	},
}

var defaultRelayRecipeRecords = map[string]map[string]any{
	"witness-falsify": {
		"purpose":              "Adversarially test filed defect witnesses against a frozen Charter.",
		"participants":         []any{"claude-code", "codex-deep"},
		"facilitator":          "codex-fast",
		"reducer":              "codex-deep",
		"mode":                 "adversarial",
		"participant_turns":    4,
		"result_source":        "reducer",
		"provider_retry":       "forbid",
		"integration_contract": "witnessed-review/witness-falsification-v1",
		"max_depth":            1,
		"auto_approval":        "never",
		"lifecycle": map[string]any{
			"resume":              "forbid",
			"steering":            "forbid",
			"dynamic":             "forbid",
			"workspace_isolation": "ephemeral",
		},
	},
	"witness-falsify-codex": {
		"purpose":              "Adversarially test filed defect witnesses against a frozen Charter.",
		"participants":         []any{"codex-deep", "codex-deep"},
		"facilitator":          "codex-fast",
		"reducer":              "codex-deep",
		"mode":                 "adversarial",
		"participant_turns":    4,
		"result_source":        "reducer",
		"provider_retry":       "forbid",
		"integration_contract": "witnessed-review/witness-falsification-v1",
		"max_depth":            1,
		"auto_approval":        "never",
		"lifecycle": map[string]any{
			"resume":              "forbid",
			"steering":            "forbid",
			"dynamic":             "forbid",
			"workspace_isolation": "ephemeral",
		},
	},
	"witness-falsify-claude": {
		"purpose":              "Adversarially test filed defect witnesses against a frozen Charter.",
		"participants":         []any{"claude-code", "claude-code"},
		"facilitator":          "claude-code",
		"reducer":              "claude-code",
		"mode":                 "adversarial",
		"participant_turns":    4,
		"result_source":        "reducer",
		"provider_retry":       "forbid",
		"integration_contract": "witnessed-review/witness-falsification-v1",
		"max_depth":            1,
		"auto_approval":        "never",
		"lifecycle": map[string]any{
			"resume":              "forbid",
			"steering":            "forbid",
			"dynamic":             "forbid",
			"workspace_isolation": "ephemeral",
		},
	},
	"witness-falsify-v2": {
		"purpose":              "Use the consumer-owned witnessed-review/witness-falsification-v2 contract.",
		"participants":         []any{"claude-code", "codex-deep"},
		"facilitator":          "codex-fast",
		"reducer":              "codex-deep",
		"mode":                 "adversarial",
		"participant_turns":    4,
		"result_source":        "reducer",
		"provider_retry":       "forbid",
		"integration_contract": "witnessed-review/witness-falsification-v2",
		"max_depth":            1,
		"auto_approval":        "never",
		"lifecycle": map[string]any{
			"resume":              "forbid",
			"steering":            "forbid",
			"dynamic":             "forbid",
			"workspace_isolation": "ephemeral",
		},
	},
	"witness-falsify-v2-codex": {
		"purpose":              "Use the consumer-owned witnessed-review/witness-falsification-v2 contract.",
		"participants":         []any{"codex-deep", "codex-deep"},
		"facilitator":          "codex-fast",
		"reducer":              "codex-deep",
		"mode":                 "adversarial",
		"participant_turns":    4,
		"result_source":        "reducer",
		"provider_retry":       "forbid",
		"integration_contract": "witnessed-review/witness-falsification-v2",
		"max_depth":            1,
		"auto_approval":        "never",
		"lifecycle": map[string]any{
			"resume":              "forbid",
			"steering":            "forbid",
			"dynamic":             "forbid",
			"workspace_isolation": "ephemeral",
		},
	},
	"witness-falsify-v2-claude": {
		"purpose":              "Use the consumer-owned witnessed-review/witness-falsification-v2 contract.",
		"participants":         []any{"claude-code", "claude-code"},
		"facilitator":          "claude-code",
		"reducer":              "claude-code",
		"mode":                 "adversarial",
		"participant_turns":    4,
		"result_source":        "reducer",
		"provider_retry":       "forbid",
		"integration_contract": "witnessed-review/witness-falsification-v2",
		"max_depth":            1,
		"auto_approval":        "never",
		"lifecycle": map[string]any{
			"resume":              "forbid",
			"steering":            "forbid",
			"dynamic":             "forbid",
			"workspace_isolation": "ephemeral",
		},
	},
	"economy-equivalence": {
		"purpose":              "Adversarially test filed deletion and simplification equivalence witnesses.",
		"participants":         []any{"claude-code", "codex-deep"},
		"facilitator":          "codex-fast",
		"reducer":              "codex-deep",
		"mode":                 "adversarial",
		"participant_turns":    4,
		"result_source":        "reducer",
		"provider_retry":       "forbid",
		"integration_contract": "witnessed-review/economy-equivalence-v1",
		"max_depth":            1,
		"auto_approval":        "never",
		"lifecycle": map[string]any{
			"resume":              "forbid",
			"steering":            "forbid",
			"dynamic":             "forbid",
			"workspace_isolation": "ephemeral",
		},
	},
	"economy-equivalence-codex": {
		"purpose":              "Adversarially test filed deletion and simplification equivalence witnesses.",
		"participants":         []any{"codex-deep", "codex-deep"},
		"facilitator":          "codex-fast",
		"reducer":              "codex-deep",
		"mode":                 "adversarial",
		"participant_turns":    4,
		"result_source":        "reducer",
		"provider_retry":       "forbid",
		"integration_contract": "witnessed-review/economy-equivalence-v1",
		"max_depth":            1,
		"auto_approval":        "never",
		"lifecycle": map[string]any{
			"resume":              "forbid",
			"steering":            "forbid",
			"dynamic":             "forbid",
			"workspace_isolation": "ephemeral",
		},
	},
	"economy-equivalence-claude": {
		"purpose":              "Adversarially test filed deletion and simplification equivalence witnesses.",
		"participants":         []any{"claude-code", "claude-code"},
		"facilitator":          "claude-code",
		"reducer":              "claude-code",
		"mode":                 "adversarial",
		"participant_turns":    4,
		"result_source":        "reducer",
		"provider_retry":       "forbid",
		"integration_contract": "witnessed-review/economy-equivalence-v1",
		"max_depth":            1,
		"auto_approval":        "never",
		"lifecycle": map[string]any{
			"resume":              "forbid",
			"steering":            "forbid",
			"dynamic":             "forbid",
			"workspace_isolation": "ephemeral",
		},
	},
	"economy-equivalence-v2": {
		"purpose":              "Use the consumer-owned witnessed-review/economy-equivalence-v2 contract.",
		"participants":         []any{"claude-code", "codex-deep"},
		"facilitator":          "codex-fast",
		"reducer":              "codex-deep",
		"mode":                 "adversarial",
		"participant_turns":    4,
		"result_source":        "reducer",
		"provider_retry":       "forbid",
		"integration_contract": "witnessed-review/economy-equivalence-v2",
		"max_depth":            1,
		"auto_approval":        "never",
		"lifecycle": map[string]any{
			"resume":              "forbid",
			"steering":            "forbid",
			"dynamic":             "forbid",
			"workspace_isolation": "ephemeral",
		},
	},
	"economy-equivalence-v2-codex": {
		"purpose":              "Use the consumer-owned witnessed-review/economy-equivalence-v2 contract.",
		"participants":         []any{"codex-deep", "codex-deep"},
		"facilitator":          "codex-fast",
		"reducer":              "codex-deep",
		"mode":                 "adversarial",
		"participant_turns":    4,
		"result_source":        "reducer",
		"provider_retry":       "forbid",
		"integration_contract": "witnessed-review/economy-equivalence-v2",
		"max_depth":            1,
		"auto_approval":        "never",
		"lifecycle": map[string]any{
			"resume":              "forbid",
			"steering":            "forbid",
			"dynamic":             "forbid",
			"workspace_isolation": "ephemeral",
		},
	},
	"economy-equivalence-v2-claude": {
		"purpose":              "Use the consumer-owned witnessed-review/economy-equivalence-v2 contract.",
		"participants":         []any{"claude-code", "claude-code"},
		"facilitator":          "claude-code",
		"reducer":              "claude-code",
		"mode":                 "adversarial",
		"participant_turns":    4,
		"result_source":        "reducer",
		"provider_retry":       "forbid",
		"integration_contract": "witnessed-review/economy-equivalence-v2",
		"max_depth":            1,
		"auto_approval":        "never",
		"lifecycle": map[string]any{
			"resume":              "forbid",
			"steering":            "forbid",
			"dynamic":             "forbid",
			"workspace_isolation": "ephemeral",
		},
	},
	"review-panel": {
		"id":                    "review-panel",
		"purpose":               "Use when an unresolved implementation or design risk needs a focused child relay.",
		"participants":          []any{"codex-deep", "codex-fast"},
		"facilitator":           "codex-fast",
		"reducer":               "codex-deep",
		"mode":                  "adversarial",
		"max_rounds":            6,
		"max_depth":             1,
		"required_capabilities": []any{},
		"auto_approval":         "ask",
		"match_keywords":        []any{},
	},
	"vision-review": {
		"id":                    "vision-review",
		"purpose":               "Use when the unresolved item depends on screenshots, images, UI, or visual inspection.",
		"participants":          []any{"gemini-vision", "codex-deep"},
		"facilitator":           "codex-fast",
		"reducer":               "codex-deep",
		"mode":                  "adversarial",
		"max_rounds":            4,
		"max_depth":             1,
		"required_capabilities": []any{"vision"},
		"auto_approval":         "ask",
		"match_keywords":        []any{"image", "screenshot", "visual", "ui", "diagram", "mockup"},
	},
	"one-pass-review": {
		"id":                    "one-pass-review",
		"purpose":               "Use when deliberation credit is low and a single focused pass is preferable.",
		"participants":          []any{"codex-fast", "codex-deep"},
		"facilitator":           "codex-fast",
		"reducer":               "codex-deep",
		"mode":                  "steelman",
		"max_rounds":            1,
		"max_depth":             2,
		"required_capabilities": []any{},
		"auto_approval":         "ask",
		"match_keywords":        []any{},
	},
}

var defaultRelayRecipes = selectedDefaultRelayRecipeRecords(defaultRelayRecipeRecords)

func selectedDefaultRelayRecipeRecords(records map[string]map[string]any) map[string]map[string]any {
	selected := make(map[string]map[string]any, len(records))
	for recipeID, record := range records {
		if !includeOptionalRelayRecipeDefaults && stringValue(record["integration_contract"]) != "" {
			continue
		}
		selected[recipeID] = cloneObject(record)
	}
	return selected
}
