#!/usr/bin/env python3
"""Render an existing convo-relay display HTML file to PDF.

This is the optional Phase 18 PDF helper boundary. It intentionally avoids
relay orchestration modules; Go owns session loading and HTML export.
"""

from __future__ import annotations

import argparse
import asyncio
from pathlib import Path
import sys


async def render_pdf(html_path: Path, pdf_path: Path) -> None:
    try:
        from playwright.async_api import async_playwright
    except ImportError as exc:
        raise RuntimeError(
            "PDF rendering requires Playwright. Install it with:\n"
            "  pip install playwright && python -m playwright install chromium"
        ) from exc

    pdf_path.parent.mkdir(parents=True, exist_ok=True)
    async with async_playwright() as p:
        async with await p.chromium.launch() as browser:
            page = await browser.new_page()
            await page.goto(html_path.resolve().as_uri())
            await page.wait_for_load_state("networkidle")
            await page.wait_for_timeout(1500)
            height = await page.evaluate("document.documentElement.scrollHeight")
            await page.pdf(
                path=str(pdf_path),
                width="820px",
                height=f"{height}px",
                print_background=True,
                margin={"top": "0px", "right": "0px", "bottom": "0px", "left": "0px"},
            )


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render display HTML to PDF.")
    parser.add_argument("html_path", help="Input HTML path generated by convo-relay")
    parser.add_argument("pdf_path", help="Output PDF path")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    html_path = Path(args.html_path)
    pdf_path = Path(args.pdf_path)
    if not html_path.is_file():
        print(f"error: HTML input does not exist: {html_path}", file=sys.stderr)
        return 2
    try:
        asyncio.run(render_pdf(html_path, pdf_path))
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
